### ISSUE TITLE
Tag t on line 31 in _includes/_layout.html is not a recognized Liquid tag.

### ISSUE THREAD

**Issue by bronsten-franques** [jerry901/jerry901.github.io#6]
Hello Jerry! 

I was trying to fork your fantastic website to build my own, but I am encountering the following error: _Your site is having problems building: The tag `t` on line 31 in `_includes/_layout.html` is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error._

The code in line 31 of `_includes/_layout.html` consists of:
```
<header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
    <div class="header-inner"> {% include _partials/header.html %} </div>
</header>
```

Any suggestions on how can I fix this?

Thanks!
-BF

**Comment by jerry901** [comment]
Hey, Thanks for having interest in my blog!
Well, i used to have the same problem as you do, I don’t remember the
detail but i was like some kind of Jekyll or Ruby version issue. can u tell
me which environment do you work on?

**Comment by bronsten-franques** [comment]
Thank you for your prompt reply! I'm running:

- `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`
- `jekyll 3.9.0`

I tried with `ruby 3.0.2`, but then I was running into some other issues, which from StackOverflow it seemed to come from the fact that `ruby 3.0.2` is not compatible with Github Pages yet (although maybe they were old posts and now you can).

Thanks again!

**Comment by bronsten-franques** [comment]
Actually my bad, I just realized that error cam from Github itself, not from my local machine, so in that case I'm actually not sure which environment that's worked in. Do you know if there's any way I can figure that out?

**Comment by bronsten-franques** [comment]
So odd, I just tried to run it locally in my machine, and it actually works! No errors printed, and I can access the site in `http://0.0.0.0:4000/`. So the error seems to be only when compiling it through Github Pages. Unfortunately, I need it to compile successfully through Github Pages in order for it to get published and show in `<my-username>.github.io`, right?

**Comment by bronsten-franques** [comment]
**Problem solved!** Playing around with the settings tab for the repo (on the Github website) I realized that if you ask to build the site from `main` instead of `source` (which is the one it came by default), the error disappears and the site builds successfully! I am attaching a screenshot of the setting. Thank you very much for taking the time to reply!

![image](https://user-images.githubusercontent.com/94883671/142990826-4d65af4d-d012-4b27-bc25-ad1acdb45342.png)

**Comment by jerry901** [comment]
i mean the version is too high. my environment is like below

ruby 2.6.3p62
jekyll 3.9.1

**Comment by jerry901** [comment]
cool! good luck!
